### ISSUE TITLE
Update/Create demos and tests

### ISSUE THREAD

**Issue by dkazanc** [vais-ral/CCPi-Regularisation-Toolkit#43]
Some work required to do Tests and Demos.

**Comment by paskino** [comment]
I've updated the test in the conda recipe. It now runs the CPU vs GPU tests and the tests `FGP` and `ROF` for both CPU and GPU. There are 5 failures: 
```
FAIL: test_TGV_CPU_vs_GPU (__main__.TestRegularisers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_test.py", line 335, in test_TGV_CPU_vs_GPU
    self.assertLessEqual(diff_im.sum() , 1)
AssertionError: 257746.02 not less than or equal to 1

======================================================================
FAIL: test_cpu_FGP_TV (__main__.TestRegularisers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_test.py", line 718, in test_cpu_FGP_TV
    self.assertLess(abs(rms_fgp-rms_fgp_exp) , tolerance)
AssertionError: 0.047729249226567377 not less than 1e-05

======================================================================
FAIL: test_cpu_ROF_TV (__main__.TestRegularisers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_test.py", line 675, in test_cpu_ROF_TV
    self.assertLess(abs(rms_rof-rms_rof_exp) , tolerance)
AssertionError: 0.0029989444238376914 not less than 1e-05

======================================================================
FAIL: test_gpu_FGP (__main__.TestRegularisers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_test.py", line 792, in test_gpu_FGP
    self.assertLess(abs(rms_fgp-rms_fgp_exp) , tolerance)
AssertionError: 0.047729245745330939 not less than 1e-05

======================================================================
FAIL: test_gpu_ROF (__main__.TestRegularisers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_test.py", line 753, in test_gpu_ROF
    self.assertLess(abs(rms_rof-rms_rof_exp) , tolerance)
AssertionError: 0.0029989436822595522 not less than 1e-05

----------------------------------------------------------------------
```

**Comment by dkazanc** [comment]
Tests now working. 
Question: There are gpu tests that running alongside cpu ones. What's going to happen if there is no gpu available, will tests fail then?

**Comment by paskino** [comment]
I guess that [here](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/master/Wrappers/Python/ccpi/filters/regularisers.py#L6) we should add a
```python

try: 
    import gpu_stuff
except ImportError:
    #send a warning and default to the CPU ones?
``` 

Currently, without the it will fail with `ImportError`, I suppose.

**Comment by dkazanc** [comment]
thanks, would be good to decouple them. I'll add more tests later

**Comment by dkazanc** [comment]
conda-build with Python 2.7 there is a following issue: 
```
from ccpi.filters.regularisers import ROF_TV, FGP_TV, SB_TV, TGV, LLT_ROF, DIFF4th
ImportError: No module named ccpi.filters.regularisers
Tests failed for ccpi-regulariser-0.10.1-np114py27_0.tar.bz2 - moving package to /dls_sw/apps/savu/savu_future/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for ccpi-regulariser-0.10.1-np114py27_0.tar.bz2 - moving package to /dls_sw/apps/savu/savu_future/miniconda/conda-bld/broken
TESTS FAILED: ccpi-regulariser-0.10.1-np114py27_0.tar.bz2
```
When tests fail, the package has been moved to `/conda-bld/broken` folder. Then if you do 
`conda install /dls_sw/apps/savu/savu_future/miniconda/conda-bld/broken/ccpi-regulariser-0.10.1-np114py27_0.tar.bz2 --use-local --force` it installs the package and modules **CAN** be imported and used without a problem. Is that the normal behaviour?

**Comment by paskino** [comment]
if the tests fail conda deletes the package. Use `--no-test` to skip them

**Comment by paskino** [comment]
why do the tests fail?

**Comment by dkazanc** [comment]
I cannot find the problem why they fail actually, there are no errors except the `ImportError`. Will look again into this tomorrow.
